### ISSUE TITLE
[SOCIAL MEDIA POST]: 1 minute informative video that teaches how to use Oppia web for learning

### ISSUE THREAD

**Issue by yigakpoa** [oppia/marketing-team#108]
### Goal

Build brand awareness

### Success Metrics

Clicks

**Comment by oladipomarvel** [comment]
@Kanupriyaoppia

**Comment by kanupriya-GuptaM** [comment]
Thanks for assigning this. I will create this video mostly till coming weekend.(saturday)

**Comment by emmanuellabubakar** [comment]
Link to video: https://drive.google.com/file/d/1HfDDsE5BXnV2B50jPqxrzBdkguzkoEh6/view?usp=drivesdk

**Comment by comfy96** [comment]
@riahtgl Please work on the caption for this issue. Thank you.
