### ISSUE TITLE
[SOCIAL MEDIA POST]:  Did You Kown?

### ISSUE THREAD

**Issue by comfy96** [oppia/marketing-team#124]
### Topic of the post

The number zero was first used in India over 5,000 years ago

### Goal

Build brand awareness

### Success Metrics

Impressions

**Comment by kanupriya-GuptaM** [comment]
@comfy96 please have a look
Facebook :
Math's is not just a subject ,It's a Journey of Empowerment through Knowledge, a lot of people worked hard to enhance its features. Zero plays a significant role from  our everyday lives to Rocket journey's ...To know more fun facts about Math's and learning with fun stay connected with Oppia and follow this link

linked in :
 "5000" Did you notice we can not even write this "five thousand" in  Numbers without a "ZERO", Indian mathematician 'Brahmagupta' invented this around the 7th century. Our Place value system, advanced mathematics  and Modern technology depends on Zero(0) .Nothingness is technically nothing but to represent this "Nothingness" we needed something and that something is Number Zero.... Be proud that Whole world worked hard to enhance the quality of mathematics and we are lucky to be born in the time when knowledge is power ...

Instagram:
  Zero is Hero of mathematics" :Read caption to know more" Zero is not just a circle , this changes the power of any other number. It was used for the first time around 5000 years ago in India, let's know some more fun facts about this placeholder:1. ZERO is the only real number that's neither positive nor negative.2.Any real number to the 0th power is one.3.0 is the additive identity: n + 0 = n and it means this also has subtractive identity n - 0 = n.4:Anything times 0 is 0: n × 0 = 0 but for your surprise you can not Divide anything with "0" as your answer will be undefined or infinity...follow our insta page and to learn math's with fun follow this link .

twitter :
 Do you know the number Zero(0) was first used in India around 5000 years ago ...To know more stay connected and to learn mathematics follow this link

Thanks
kanupriya
