### ISSUE TITLE
[ADMIN]: repo is public but states is private

### ISSUE THREAD

**Issue by arthurzenika** [oppia/marketing-team#152]
### Description of the task

Hi, not sure if this is a problem but as an outsider from oppia I can see this repo and it states it's private. Hope this helps.

**Comment by seanlip** [comment]
Thanks @arthurzenika! That documentation is out of date, I went and dropped the "Private" word from the README. Thanks for bringing it to our attention!

( /cc @yigakpoa @PrettyNneoma for info)

**Comment by arthurzenika** [comment]
The description of the repo still says "Private"

**Comment by yigakpoa** [comment]
Corrected in the “about section” @arthurzenika thank you
