### ISSUE TITLE
Hello everyone, our last meeting for this contribution period is tomorrow. Please come prepared with all your unanswered questions. Thank you

### ISSUE THREAD

**Issue by Deborah-M-Oyawale** [oppia/marketing-team#198]
Hello everyone, our last meeting for this contribution period is tomorrow. Please come prepared with all your unanswered questions. Thank you

What time is the meeting please?

_Originally posted by @erioc in https://github.com/oppia/marketing-team/discussions/149#discussioncomment-11045311_

**Comment by erioc** [comment]
Mentor Meet & Greet
Friday, Oct 25  •  3:00 – 4:00 PM (GMT+1)
Google Meet joining info
Video call link: https://meet.google.com/nuc-eohf-vfe
Or dial: +256 41 4238009 PIN: 840 600 201 2516#
More phone numbers: https://tel.meet/nuc-eohf-vfe?pin=8406002012516
